name: z_ignore

on:
  pull_request:

jobs:
  z_ignore:
    runs-on: ubuntu-latest
    steps:      
      - name: Fetch schedule from pagerduty
        id: pagerduty
        uses: actions/github-script@v5
        with:
          script: |
            const fetch = require('node-fetch');
            const response = await fetch('https://api.pagerduty.com/schedules/P3IIVC4', {
              headers: {
               'Content-Type': 'application/json',
               'Authorization': 'Token token=${{ secrets.PAGERDUTY_API_KEY_SID }}'
              }
            })
            const data = await response.json()
            console.log(data)
            console.log(data.schedule.final_schedule.rendered_schedule_entries[0].user.summary)
            
            return data.schedule.final_schedule.rendered_schedule_entries[0].user.summary
            
      - run: echo ${{ steps.pagerduty.outputs.result }} is release conductor

      - name: Assign pull request to release conductor
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ steps.pagerduty.outputs.result }}
          reviewers: ${{ steps.pagerduty.outputs.result }}
