name: Assign Release Conductor

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pull-request:
        type: number
        description: Pull Request Number
        required: true

jobs:
  assign-release-conductor:
    if: ${{ github.head_ref == 'changeset-release/main' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - uses: ./.github/actions/pagerduty
        id: pagerduty
        with:
          schedule-id: 'P3IIVC4'
          token: ${{ secrets.PAGERDUTY_API_KEY_SID }}
      - run: echo ${{ steps.pagerduty.outputs.user }} is release conductor
      - name: Remove previous conductor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.inputs.pull-request || github.event.pull_request.number }}
          PREV_RELEASE_CONDUCTOR: ${{ steps.pagerduty.outputs.previous-schedule-user }}
        run: |
          # Remove as assignee
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/issues/$PR/assignees" \
            -f "assignees[]=$PREV_RELEASE_CONDUCTOR"

          # Remove as requested reviewer
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/pulls/$PR/requested_reviewers" \
            -f "reviewers[]=$PREV_RELEASE_CONDUCTOR"
      - name: Add current conductor as assignee and reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.inputs.pull-request || github.event.pull_request.number }}
          RELEASE_CONDUCTOR: ${{ steps.pagerduty.outputs.user }}
        run: |
          # Add as assignee
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/issues/$PR/assignees" \
            -f "assignees[]=$RELEASE_CONDUCTOR"

          # Add as requested reviewer
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/pulls/$PR/requested_reviewers" \
            -f "reviewers[]=$RELEASE_CONDUCTOR"
