name: Assign Release Conductor

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pull-request:
        type: number
        description: Pull Request Number
        required: true

jobs:
  assign-release-conductor:
    if: ${{ github.head_ref == 'changeset-release/main' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - uses: ./.github/actions/pagerduty
        id: pagerduty
        with:
          schedule-id: 'P3IIVC4'
          token: ${{ secrets.PAGERDUTY_API_KEY_SID }}
      - run: echo ${{ steps.pagerduty.outputs.user }} is release conductor
      - name: Remove previous conductor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.inputs.pull-request || github.event.pull_request.number }}
          PREV_RELEASE_CONDUCTOR: ${{ steps.pagerduty.outputs.previous-schedule-user }}
        run: |
          gh pr edit $PR --remove-assignee $PREV_RELEASE_CONDUCTOR
          gh pr edit $PR --remove-reviewer $PREV_RELEASE_CONDUCTOR
      - name: Add current conductor as assignee and reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.inputs.pull-request || github.event.pull_request.number }}
          RELEASE_CONDUCTOR: ${{ steps.pagerduty.outputs.user }}
        run: |
          gh pr edit $PR --add-assignee $RELEASE_CONDUCTOR
          gh pr edit $PR --add-reviewer $RELEASE_CONDUCTOR
