name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test -- --coverage

      - name: Type check
        run: npm run test:type-check

      - name: Install dependencies for examples
        working-directory: examples/nextjs
        run: npm ci

  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [nextjs, consumer-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install example dependencies
        run: npm ci
        working-directory: examples

      - name: Build example
        run: npm run --if-present build
        working-directory: examples/${{ matrix.example }}

      - name: Run checks
        run: npm run --if-present check
        id: check
        working-directory: examples/${{ matrix.example }}

      - name: Add annotation
        if: failure() && steps.check.conclusion == 'failure' && matrix.example == 'consumer-test'
        run: |
          echo "::error file=tsconfig.build.json::Test package could not build. See https://github.com/primer/react/blob/main/examples/consumer-test"
