name: Cypress Tests
on:
  workflow_run:
    workflows: [Deploy]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 120
          browser: chrome
          record: true
          command: npm run cypress:tests -- --config baseUrl=$${{github.event.workflow_run.steps.vercel-action.outputs.preview-url}}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
