name: Deploy
on:
  pull_request:
  push:
    branches-ignore:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-preview:
    if: ${{ github.repository == 'primer/react' }}
    name: Preview
    uses: primer/.github/.github/workflows/deploy_preview.yml@main
    with:
      node_version: 16
      install: cd docs && npm run install
      build: cd docs && npm run build:preview
      output_dir: docs/public
