name: Deploy
on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-preview:
    if: ${{ github.repository == 'primer/react' }}
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with Pages
        uses: primer/.github/.github/workflows/deploy_preview.yml@main
        with:
          build: cd docs && npm run build:preview
          output_dir: docs/public
