name: Test

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  guard:
    name: Guard
    runs-on: ubuntu-latest
    outputs:
      # To avoid deploying documentation for unrelease changes, we check the number of changeset files.
      # If it's 0, we deploy.
      change_count: ${{ steps.changeset-count.outputs.change_count }}
      should_deploy: ${{ steps.changeset-count.outputs.change_count == 0 }}
    steps:
      - uses: actions/checkout@v2

      - id: changeset-count
        run: echo "::set-output name=change_count::$(ls .changeset/*.md | grep -v README | wc -l | xargs)"

      # Log changeset count for debugging purposes
      - name: Log changeset count
        run: echo ${{ steps.changeset-count.outputs.change_count }}

  deploy:
    name: Production
    needs: guard
    steps:
      - run: echo needs.guard.outputs.change_count
      - run: echo needs.guard.outputs.should_deploy
