name: Deploy
on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-preview:
    # if the source repository for pull request is a fork, we don't want to run this workflow,
    # we run deploy_preview_forks.yml which uses pull_request_target instead.
    # see https://github.com/primer/react/pull/2207 for details
    if: ${{ github.event.pull_request.head.repo.full_name == 'primer/react' }} # source repository for pull_request
    name: Preview
    uses: primer/.github/.github/workflows/deploy_preview.yml@0cec9b9914f358846163f2428663b58da41028c9
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      node_version: 14
      install: npm ci && cd docs && npm ci && cd ..
      build: npm run build:docs:preview
      output_dir: docs/public
  deployment_url:
    runs-on: ubuntu-latest
    needs: deploy-preview
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - run: echo ${{ steps.package-version.outputs.current-version}}
      - run: echo {} > deployments.json
      - name: Update deployment url in artifact
        uses: jossef/action-set-json-field@v2
        with:
          file: deployments.json
          field: ${{ steps.package-version.outputs.current-version}}
          value: ${{needs['deploy-preview'].outputs.deployment_url}}
      - run: cat deployments.json
      - name: Upload file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deployments.json
          path: deployments.json
