name: Deploy
on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deployments_cache:
    runs-on: ubuntu-latest
    # needs: deploy-preview
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # setup    
      - name: Get cached deployments.json
        uses: actions/cache@v3
        id: cached
        with:
          path: deployments.json
          key: deployments.json-${{ github.run_id }} # https://github.com/actions/cache/blob/main/workarounds.md#update-a-cache
          restore-keys: deployments.json
      - run: echo cache-hit ${{steps.cached.outputs.cache-hit}}
      - run: cat deployments.json

      # add deployment url
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - run: echo ${{ steps.package-version.outputs.current-version}}
      - name: Update deployment url in deployments.json
        uses: jossef/action-set-json-field@v2
        with:
          file: deployments.json
          field: '${{ steps.package-version.outputs.current-version}}'
          value: ${{'TODO' || needs['deploy-preview'].outputs.deployment_url}}
      - run: cat deployments.json
