name: Deploy

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Production
    uses: primer/.github/.github/workflows/deploy.yml@main
    with:
      node_version: 14
      install: npm ci && cd docs && npm ci
      build: npm run build
      output_dir: docs/public
