name: One time unpublish
on:
  push:
  workflow_dispatch:

jobs:
  one_time_unpublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
      - name: Unpublish 0.0.0-2021118184718
        run: npm unpublish @primer/react@0.0.0-2021118184718 --loglevel silly
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
