name: Integration tests for Primitives in Primer React
run-name: Integration tests for ${{github.event.inputs.primitives-pr}} and version ${{github.event.inputs.version}}

on:
  push:
    branches:
      - primitives-integration-pr
#   workflow_dispatch:
#     inputs:
#       primitives-pr:
#         required: true
#         description: 'Paste the link of the PR you would like to test (This could be release Pr as well)'
#         type: string
#       version:
#         required: true
#         description: 'Specify the canary version of the above PR you would like to test'
#         type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  # Check if there is an integration PR for the specified Primitives PR
  check-integration-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get the PR number from the given PR URL
        id: get-pr-number
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = '${{ github.event.inputs.primitives-pr }}'.split('/').pop()
            return Number(prNumber)
      - name: Check if integration PR exists for the specified Primitives PR
        id: does-pr-exist
        uses: actions/github-script@v6
        with:
          script: |
            const allPulls = await github.rest.pulls.list({
               owner: context.repo.owner,
               repo: context.repo.repo,
               per_page: 100
            });
            const pulls = await github.paginate(allPulls)
            const result = pulls.find((pull) => {
              const prExist = pull.head.ref == 'prc-integration-test-for-' + '${{ steps.get-pr-number.outputs.result }}'
              return prExist ? pull : false
            });
            return result
      - run: echo "Does PR exist? - ${{ steps.does-pr-exist.outputs.result != false }}"
    outputs:
      prExists: ${{ steps.does-pr-exist.outputs.result }}
  create-integration-pr:
    needs: check-integration-pr
    runs-on: ubuntu-latest
    if: ${{ needs.check-integration-pr.outputs.prExists == false }}
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 902635
          private-key: ${{ secrets.PRIMER_INTEGRATION_APP_PRIVATE_KEY }}
          owner: 'primer'
          repositories: 'react'
      - name: Get the PR number from the given PR URL
        id: get-pr-number
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = '${{ github.event.inputs.primitives-pr }}'.split('/').pop()
            return Number(prNumber)
      - run: echo "Thanks for testing your Primitives changes at Primer React!"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm i @primer/primitives@0.0.0-20240515005243
      #   - name: Update @primer/primitives version on package.json with the specified version number
      #     id: primitives-version
      #     uses: actions/github-script@v6
      #     with:
      #       script: |
      #         const fs = require('fs')
      #         const pkg = require('./packages/react/package.json')
      #         const package = pkg.dependencies['@primer/primitives']

      #         const specifiedVersion = '0.0.0-20240515005243'
      #         console.log('Current version of @primer/primitives - ', package)
      #         if(package != specifiedVersion) {
      #           pkg.dependencies[@primer/primitives'] = specifiedVersion
      #           fs.writeFileSync('./packages/react/package.json', JSON.stringify(pkg, null, 2))
      #         }
      #         return pkg.dependencies['@primer/primitives']

      - name: Install dependencies
        run: npm ci

      # Create a new PR with the specified canary version
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          base: main
          branch: 'prc-integration-test-for-${{ steps.get-pr-number.outputs.result }}'
          draft: true
          delete-branch: true
          commit-message: 'Integration tests for PRC ${{ github.event.inputs.version }}'
          title: 'Integration tests for Primitives PR ${{steps.get-pr-number.outputs.result}}'
          body: |
            <!-- primitives-pr-number: #${{steps.get-pr-number.outputs.result}} -->
            ⚠️ Please do not merge this PR.

            - Auto-generated by [primer-react-pr-rest github action](https://github.com/primer/react/.github/workflows/primitives-integration-pr.yml)
            - This PR is created to test the integration of Primer Primitives changes in the PR of ${{ github.event.inputs.primitives-pr }} with primer/react.

            **Once the integration tests are completed, please close the PR.**
          labels: |
            skip changeset
      - name: Print Pull Request URL
        if: ${{ steps.cpr.outputs.pull-request-url }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
