name: Pull request
on:
  pull_request_target:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.ref_name }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.base_ref }}"
      - run: echo "${{ github.event }}"
      - run: echo "${{ github.event_name }}"