name: Release

on:
  push:
    branches:
      - main
      - next-major

jobs:
  release-main:
    if: github.ref_name == 'main'
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo 'TODO'

  release-next-major:
    if: github.ref_name == 'next-major'
    name: Next major
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo 'TODO'
