name: Release

on:
  push:
    branches:
      - 'changeset-release/main'
      - 'changeset-release/next-major'

jobs:
  release-candidate:
    if: github.ref_name == 'changeset-release/main'
    name: Candidate (@next)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo 'TODO'

  release-candidate-next-major:
    if: github.ref_name == 'changeset-release/next-major'
    name: Candidate (@next-major)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo 'TODO'
