name: Canary Release
on:
  push:
    branches-ignore:
      - 'main'
      - 'next-major'
      - 'changeset-release/**'

jobs:
  release:
    concurrency: npm-canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo 'TODO'
