name: Report results of integration tests

# using label for now, will think about this a little more
on:
  pull_request:
    types: [labeled]

jobs:
  report-results:
    runs-on: ubuntu-latest
    steps:
      - id: get-github-access-token
        uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_ID_FOR_GITHUB }}
          private-key: ${{ secrets.PRIMER_ISSUE_TRIAGE_APP_PRIVATE_KEY_FOR_GITHUB }}
          client-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_CLIENT_ID_FOR_GITHUB }}
          client-secret: ${{ secrets.PRIMER_ISSUE_TRIAGE_APP_CLIENT_SECRET_FOR_GITHUB }}
          installation-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_INSTALLATION_ID_FOR_GITHUB }}

      - name: Get workflow run
        uses: actions/github-script@v7
        env:
          BRANCH: "prc-integration-test-for-${{github.event.pull_request.number}}"
          WORKFLOW_ID: "primer-react-pr-test.yml"
          GH_TOKEN: ${{ steps.get-github-access-token.outputs.access-token }}
        with:
          script: |
            const { BRANCH, WORKFLOW_ID } = process.env;

            const { data: workflow_runs } = await github.rest.actions.listWorkflowRuns({
              owner: 'github',
              repo: 'github',
              workflow_id: WORKFLOW_ID,
              branch: BRANCH
            });

            console.log(workflow_runs)
