name: Report results of integration tests

# using label for now, will think about this a little more
on:
  # temporary so I can test this
  push:
  pull_request:
    types: [labeled]

jobs:
  report-results:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: get-github-access-token
        uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_ID_FOR_GITHUB }}
          private-key: ${{ secrets.PRIMER_ISSUE_TRIAGE_APP_PRIVATE_KEY_FOR_GITHUB }}
          client-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_CLIENT_ID_FOR_GITHUB }}
          client-secret: ${{ secrets.PRIMER_ISSUE_TRIAGE_APP_CLIENT_SECRET_FOR_GITHUB }}
          installation-id: ${{ vars.PRIMER_ISSUE_TRIAGE_APP_INSTALLATION_ID_FOR_GITHUB }}
      - id : get-workflow-run
        name: Get workflow run
        uses: actions/github-script@v7
        env:
          # BRANCH: "prc-integration-test-for-${{github.event.pull_request.number}}"
          BRANCH: "prc-integration-test-for-4358"
          WORKFLOW_ID: "primer-react-pr-test.yml"
          RUN_NAME: 'GitHub CI - Actions'
        with:
          # github-token: ${{ steps.get-github-access-token.outputs.access-token }}
          github-token: ${{ secrets.TEMP_SID_PAT }}
          script: |
            const { BRANCH, WORKFLOW_ID, RUN_NAME } = process.env;

            const { data } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: 'github',
              repo: 'github',
              branch: BRANCH
            });

            const run = data.workflow_runs.find(run => run.name === RUN_NAME)
            core.setOutput('id', run.id);
            core.setOutput('html_url', run.html_url);
      - id: get-golden-jobs-results
        name: Get golden-jobs-results
        uses: actions/github-script@v7
        env:
          RUN_ID: ${{steps.get-workflow-run.outputs.result.id}}
          JOB_NAME: 'golden-jobs-results'
        with:
          # github-token: ${{ steps.get-github-access-token.outputs.access-token }}
          github-token: ${{ secrets.TEMP_SID_PAT }}
          script: |
            const { RUN_ID, JOB_NAME } = process.env;

            const { data } = await github.rest.actions.listJobsForWorkflowRun({
              owner: 'github',
              repo: 'github',
              run_id: RUN_ID,
              per_page: 100,
              page: 2,
            });

            const {status, conclusion, html_url} = data.jobs.find(job => job.name === JOB_NAME)

            console.log({status, conclusion, html_url})
            return {status, conclusion, html_url}
