name: Test
on:
  push:
    branches:
      - 'changeset-release/main'
      - 'test-rc-action'

permissions:
  contents: read

jobs:
  say-hi:
    if: ${{ github.repository == 'primer/react' }}
    name: Hi
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Trigger a workflow
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.github_token }}
          script: |
            github.actions.createWorkflowDispatch({
              owner: 'primer',
              repo: 'react',
              workflow_id: 'test-action.yml',
              ref: 'test-rc-action'
            });
