name: Temporary
on:
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  get_cached_value:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: github.head_ref
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
