name: Temporary
on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  get_cached_value:
    runs-on: ubuntu-latest
    steps:
      - name: Get script
        uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          script: return "Hello!"
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
