name: VRT
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  chromatic:
    name: Visual testing
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const fs = require('fs');

            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            const [matchArtifact] = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "storybook"
            });
            const download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });

            fs.writeFileSync('${{github.workspace}}/storybook.zip', Buffer.from(download.data));

      - run: unzip storybook.zip
      - name: Install dependencies
        run: npm ci

      - name: Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_KEY }}
          autoAcceptChanges: github.ref == 'refs/heads/main'
          onlyChanged: true
          storybookBuildDir: storybook-static
